package replaydriver;

// generated by CLAP on Tue Feb 28 00:38:50 HKT 2012
// Created for XXX JVM: R27.6.3-40_o-112056-1.6.0_11-20090318-2103-linux-x86_64
import edu.hkust.clap.tracer.*;
import edu.hkust.clap.replayer.*;

public class ReplayDriver {

	public static void setUp(String[] args) throws Exception {
		TraceReader.setFileIndex(args);
		TraceReader.readTrace(1,"/home/lpxz/eclipse/workspace/pecan/pecan-replayer/tmp/Clap7874357457353106837_monitordata.trace.gz");
		TraceReader.readTrace(2,"/home/lpxz/eclipse/workspace/pecan/pecan-replayer/tmp/Clap7874357457353106837_threadNameToIdMap.trace.gz");
	}

	public static void main(String[] args) throws Throwable {

		setUp(args);

		new Thread("clap-main"){
			public void run(){
				// load arguments
				String[] mainargs = {};
				try {
					spec.jbb.JBBmain.main(mainargs);
				} catch (Throwable e) {
					e.printStackTrace();
				}
			}
		}.start();

		(new Scheduler()).start();

		//WAIT FOR 1 MINUTE TO STOP REPLAY
		//Thread.currentThread().sleep(60000);
	}
}

